# Generated by Django 4.2 on 2025-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('notesfile', models.FileField(upload_to='Notes')),
            ],
        ),
    ]
